name: hello world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world
        run: echo "Hello world"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    #  - name: Checkout
    #    uses: actions/checkout@v2
      - name: Deploy
        run: echo "good bye world123"
        shell: bash